apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: mayur0319/test:v2
        imagePullPolicy: Always   # 🔥 IMPORTAN
        envFrom:
        - configMapRef:
            name: app-config
        volumeMounts:
        - name: secret-volume
          mountPath: /mnt/secrets
          readOnly: true
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "300m"
            memory: "100Mi"
      volumes:
      - name: secret-volume
        secret:
          secretName: app-secret